after_success:
- coveralls
before_install:
- pip install coveralls
env:
- !!python/unicode '_DJANGO=1.10'
- !!python/unicode '_DJANGO=1.10.2'
- !!python/unicode '_DJANGO=1.10.3'
- !!python/unicode '_DJANGO=1.10.4'
- !!python/unicode '_DJANGO=1.8.14'
- !!python/unicode '_DJANGO=1.8.15'
- !!python/unicode '_DJANGO=1.8.16'
- !!python/unicode '_DJANGO=1.8.17'
- !!python/unicode '_DJANGO=1.9.10'
- !!python/unicode '_DJANGO=1.9.11'
- !!python/unicode '_DJANGO=1.9.12'
- !!python/unicode '_DJANGO=1.9.8'
- !!python/unicode '_DJANGO=1.9.9'
install:
- pip install Django==$_DJANGO
- pip install -e .
- pip install -r requirements.txt
language: python
matrix:
  exclude:
  - env: _DJANGO=1.9.8
    python: 3.3
  - env: _DJANGO=1.9.9
    python: 3.3
  - env: _DJANGO=1.9.10
    python: 3.3
  - env: _DJANGO=1.9.11
    python: 3.3
  - env: _DJANGO=1.9.12
    python: 3.3
  - env: _DJANGO=1.10
    python: 3.3
  - env: _DJANGO=1.10.2
    python: 3.3
  - env: _DJANGO=1.10.3
    python: 3.3
  - env: _DJANGO=1.10.4
    python: 3.3
notifications:
  email:
    on_failure: change
    on_success: change
python:
- 2.7
- 3.3
- 3.4
- 3.5
script: make coverage
